#!/usr/bin/env php
<?php declare(strict_types=1);


require_once '/var/www/vendor/autoload.php';

$dbname = getenv('MYSQL_DATABASE');
$dbuser = getenv('MYSQL_USER');
$dbpassword = getenv('MYSQL_PASSWORD');
$dbcontainer = getenv('CONTAINER_MYSQL');

$pdo = new PDO("mysql:host=$dbcontainer;dbname=$dbname", $dbuser, $dbpassword);

/**
* Suppression de table
*/ 
$pdo->exec('SET FOREIGN_KEY_CHECKS = 0');

$pdo->exec('DROP TABLE post');
$pdo->exec('DROP TABLE category');
$pdo->exec('DROP TABLE task');

$pdo->exec('SET FOREIGN_KEY_CHECKS = 1');

/**
 * creation tables
 * 
 */

echo "[";

$pdo->exec("CREATE TABLE post(
            id INT UNSIGNED NOT NULL AUTO_INCREMENT,
            name VARCHAR(255) NOT NULL,
            slug VARCHAR(255) NOT NULL,
            content TEXT(650000) NOT NULL,
            category_id INT UNSIGNED NOT NULL,
            created_at DATETIME NOT NULL default CURRENT_TIMESTAMP,
            PRIMARY KEY(id)
            )
");

echo "||";

$pdo->exec("CREATE TABLE category(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL default CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
    )
");

echo "||";

$pdo->exec("CREATE TABLE task(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL default CURRENT_TIMESTAMP,
    done_at DATETIME NULL,
    PRIMARY KEY(id)
    )
");

echo "||";

echo "||||]".PHP_EOL;